FROM python:3.8
WORKDIR /app

# Copy only the requirements file to leverage Docker cache
COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

# Copy the entire application to the container
COPY . .

# Specify the command to run your application
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "80"]
